language: go
notifications:
  email:
    on_success: change
    on_failure: change

install:
  - go get -u github.com/kardianos/govendor
  - govendor get github.com/gohugoio/hugo

script:
  - hugo
  - echo "eda.ai" > public/CNAME # required for GitHub Pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: source

