baseurl = "http://eda.ai"
languageCode = "en-us"
title = "IDEA EDA"
[params]
  topBlockTitle = "IDEA EDA"
  topBlockDescription = "A modern and intelligent Schematic & PCB Editor"
  mainIcon = "img/librepcb.png"
  blogTitle = "IDEA EDA Blog"
