baseurl = "http://eda.ai"
languageCode = "en-us"
title = "IDEA EDA"
[params]
  topBlockTitle = "IdeaEDA"
  topBlockDescription = "A modern and intelligent Schematic & PCB Editor"
  mainIcon = "img/librepcb.png"
  blogTitle = "IdeaEDA Blog"
