baseurl = "http://eda.ai"
languageCode = "en-us"
title = "IdeaEDA"
[params]
  topBlockTitle = "IdeaEDA"
  topBlockDescription = "A new, powerful and intuitive EDA tool for everyone."
  mainIcon = "img/librepcb.png"
  blogTitle = "IdeaEDA Blog"
